# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/User-Identity-0.92

DESCRIPTION="Define a person"
HOMEPAGE="http://search.cpan.org/search?query=User-Identity&mode=dist"
SRC_URI="mirror://cpan/authors/id/M/MA/MARKOV/User-Identity-0.92.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64"

DEPEND=">=dev-perl/Test-Pod-1.26
	dev-lang/perl"
