# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Mail-Transport-Dbx-0.07

DESCRIPTION="Parse Outlook Express mailboxes"
HOMEPAGE="http://search.cpan.org/search?query=Mail-Transport-Dbx&mode=dist"
SRC_URI="mirror://cpan/authors/id/V/VP/VPARSEVAL/Mail-Transport-Dbx-0.07.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64"

