#!/usr/bin/perl

use 5.010;
use POSIX qw(strftime);

use IO::Socket;

my $server = IO::Socket::INET->new(
 LocalPort => 5140,
 Proto     => "udp")
 or die "Couldn't listen on metalog port : $@\n";

my $MAX_TO_READ = 1500;
my $flags = 0;
my $datagram;

while ($server->recv($datagram, $MAX_TO_READ)) {
	if ($datagram =~ /^<(?<prio>\d)(?<service>\d)(?<truc>\d?)>(?<month>\S+)\s+(?<day>\d+) (?<hour>\S+) (?<logger>.+?): (?<message>.*)$/) {
		my $date = strftime("%F_%T", localtime);
		print "[33m$date[0m [32m$+{logger}[0m $+{message}\n";
	}
	else {
		print "unparsed : $datagram";
	}
}

__END__

Provides a metalog console, used when NETLOG goes to localhost
