#!/bin/sh
# Provides a metalog console, used when NETLOG goes to localhost


socat udp-recv:5140 - \
 | perl -e \
 '
use POSIX qw(strftime);
while (<>) {
 if (/^\S+\s+\s+\S+ \S+ (.+): (.*)$/) {
  my $date = strftime("%F_%T", localtime);
  print "\e[33m$date\e[0m \e[32m$1\e[0m $2\n";
 }
 else {
  print "$_";
 }
}
'
